version: "3.7"
services:
  db:
    image: postgres:latest
    container_name: agro-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: agro-db

